'use strict';

import menu from './modules/menu.js';
import repairData from './modules/repairData.js';
import openRepair from './modules/openRepair.js';
import popupRepair from './modules/popupRepair.js';
import tabRepairSlider from './modules/tabRepairSlider.js';
import repairNavSlider from './modules/repairNavSlider.js';
import mask from './modules/maskPhone.js';
import sendForm from './modules/sendForm.js';
import privacy from './modules/privacy.js';
import successBlock from './modules/successBlock.js';
import portfolio from './modules/portfolio.js';
import transparencySlider from './modules/transparencySlider.js';
import consultation from './modules/consultation.js';
import reviews from './modules/reviews.js';
import accordion from './modules/accordion.js';

menu();
repairData();
openRepair(0);
popupRepair();
tabRepairSlider();
repairNavSlider();
mask();
sendForm();
privacy();
successBlock();
portfolio();
transparencySlider();
consultation();
reviews();
accordion();